on:
 push:
  branches:
  - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: echo java version
      run: java -version
    - name: cpu info
      run: cat /proc/cpuinfo
